exports.logo = function(){
  /* Surely there's a more elegant way? */
  console.log("                               .");
  console.log("                             . ");
  console.log("                             , ");
  console.log("                            ., ");
  console.log("                            .:    ");
  console.log("                            ,:       ");
  console.log("                            ;:          ");
  console.log("                           ,i,            ");
  console.log("                          .;;.  .         ");
  console.log("            .             :i:  ..         ");
  console.log("            ,            ,ii.  .,         ");
  console.log("           .,           .;i:   ,,         ");
  console.log("         . .,          .;ii.   :.         ");
  console.log("        .. ,,          :ii:   .:.         ");
  console.log("        .. ,:         ,ii;    ,:          ");
  console.log("        .. ,:        ,;i;.   .:,          ");
  console.log("        ., ,;.      ,;i;,   .::.          ");
  console.log("        ., .;,     ,;i;:    ,;:           ");
  console.log("        .,  ;:    ,;ii:    ,;:.           ");
  console.log("        .,. :;   .;ii:.   ,;;,            ");
  console.log("         ,, .;, .;;i;.   ,:;:.            ");
  console.log("         ,,  ;,.:;;;.   .:;:.             ");
  console.log("         .,  :::;;;.   .:::,              ");
  console.log("          ,. .;;;:.   .:::,               ");
  console.log("          ,. .;;;.   .:::,                ");
  console.log("          .. :;;,   .:::,                 ");
  console.log("          ...;;,   .:::,        ..        ");
  console.log("          ..:;:   .:::,       .,,.        ");
  console.log("           .;;.  .,::,...,,,,:::...       ");
  console.log("           ,;,   ,::::::::::,,,..:.       ");
  console.log("           ,:   .::::,,,......,,;:        ");
  console.log("           :,  .,:,,...,,:::;;;;:.        ");
  console.log("           :.  ,:,  .,:;;ii;;;:,          ");
  console.log("           ,   ,,. .;;;::,,..             ");
  console.log("           .  .,. .;:.                    ");
  console.log("           .  .,  :.                      ");
  console.log("              .. ..                       ");
  console.log("              ..                          ");
  console.log("              .                           ");
};
